# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8bb1d1c8fa02e79331371b1225ac854d4091534b6324ddeead69db76d5b51beb268da49269c8a0846e370d16cda7511b01571a52c3142aeca1c293aeaa4d976

test:
  secret_key_base: 05e3790c2174fccc36b2e8514dc6a6c953888a3acbdbc239bebab0c42b03ef14ca15c2a792d175994192259ecda98d18d52ae7bfce52ace66265aa83c5fa2795

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
